### PR TITLE
print output of failed prepublish scripts #441

### LINKED ISSUE #441: Show `vscode:prepublish` script output even if it failed
A simple script like `echo foobar` prints this:

```
> npx vsce package
npx: installed 67 in 4.988s
Executing prepublish script 'npm run vscode:prepublish'...

> sample-extension@0.0.1 vscode:prepublish /home/iliazeus/Repositories/sample-extension
> echo foobar

foobar
 DONE  Packaged: /home/iliazeus/Repositories/sample-extension/sample-extension-0.0.1.vsix (5 files, 2.04KB)
```

But if i change it to fail (`echo foobar && exit 1`), it prints this:

```
> npx vsce package              
npx: installed 67 in 4.731s
Executing prepublish script 'npm run vscode:prepublish'...
 ERROR  Command failed: npm run vscode:prepublish
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sample-extension@0.0.1 vscode:prepublish: `echo foobar && exit 1`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sample-extension@0.0.1 vscode:prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iliazeus/.npm/_logs/2020-04-17T07_44_46_912Z-debug.log
```

Notice that `foobar` is missing from the second output.

It makes it hard, for example, to debug prepublish script errors running in a CI pipeline.

### PR DESCRIPTION
**Pull request by iliazeus**
This PR fixes #441

### CODE REVIEW

**Comment by iliazeus** [comment]
https://github.com/iliazeus/vscode-vsce/commit/c21dcad6ca46bac1bd5b88f75e1d90abbc80571b wasn't good enough, because it caused stderr to be doubled

File: src/package.ts [hunk 1]
```diff
@@ -929,8 +929,10 @@ async function prepublish(cwd: string, manifest: Manifest, useYarn: boolean = fa
 
 	console.log(`Executing prepublish script '${useYarn ? 'yarn' : 'npm'} run vscode:prepublish'...`);
 
-	const { stdout, stderr } = await exec(`${useYarn ? 'yarn' : 'npm'} run vscode:prepublish`, { cwd, maxBuffer: 5000 * 1024 });
+	const { stdout, stderr, error } = await exec(`${useYarn ? 'yarn' : 'npm'} run vscode:prepublish`, { cwd, maxBuffer: 5000 * 1024 });
 	process.stdout.write(stdout);
+	// in case of error, stderr gets written by a top-level exception handler
+	if (error !== undefined) throw error;
 	process.stderr.write(stderr);
```
Comment (joaomoreno) [inline src/package.ts:936]: Maybe also print stderr.

```suggestion
	process.stderr.write(stderr);
	// in case of error, stderr gets written by a top-level exception handler
	if (error) {
		throw error;
	}
```

Comment (iliazeus) [reply src/package.ts:936]: Well, I don't know for sure why that happens yet, but (as I said in the comment) stderr gets printed anyway when the exception is thrown and caught somewhere on top. That is, if we print it here explicitly, it gets printed _twice_.

My guess is that the `message` of an `Error` that gets thrown by `exec()` is set to contain the `stderr` of a child process. Or maybe `toString()` of this `Error` gives us that.

Comment (iliazeus) [reply src/package.ts:936]:
```
Welcome to Node.js v13.12.0.
Type ".help" for more information.
> const cp = require('child_process')
undefined
> let error
undefined
> void cp.exec('>&2 echo this gets printed to stderr && exit 1', e => error = e)
undefined
> error.toString()
'Error: Command failed: >&2 echo this gets printed to stderr && exit 1\n' +
  'this gets printed to stderr \r\n'
> error.message
'Command failed: >&2 echo this gets printed to stderr && exit 1\n' +
  'this gets printed to stderr \r\n'
```

**Comment by joaomoreno** [comment]
Thanks! Ended up replacing `exec` with `spawn`, which gives us the ability to inherit stdio, keep order of messages and clears the double error output issue.
